DROP TABLE IF EXISTS files;

CREATE TABLE files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    token VARCHAR(64) NOT NULL UNIQUE,
    uploaded_by VARCHAR(255) NOT NULL,
    expiry BOOLEAN NOT NULL,
    expiry_date DATETIME NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
